/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.iatom.rfm69;

import java.util.Map;

public class RFM69 {

    private IPeripheral chip;
    private Map<Byte, Register> registers;
}
