/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.iatom.rfm69;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RFM69Test {
    @Test
    void someLibraryMethodReturnsTrue() {
        RFM69 classUnderTest = new RFM69();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
